#pragma once

namespace PTML
{
	void COLOR();
	void COLOR_MODE();
	void COLOR_SETF();
	void COLOR_SETB();
	void COLOR_SETBR();
	void PRINT();
	void PRINTL();
	void PRINTF();
	void CLS();
	void PAL();
	void CHR();
	void LOAD_PAL();
	void SAVE_PAL();
	void LOAD_CHR();
	void SAVE_CHR();
	void LOAD_BUF();
	void SAVE_BUF();
	void LOCATE();
	void CSR_SETX();
	void CSR_SETY();
	void CSR_GETX();
	void CSR_GETY();
	void FULLSCR();
	void CURSOR();
	void TILE_NEW();
	void TILE_ADD();
	void TILE_SETC();
	void TILE_GETC();
	void TILE_SETF();
	void TILE_GETF();
	void TILE_SETB();
	void TILE_GETB();
	void TILE_SETP();
	void TILE_GETP();
	void PUT();
	void RECT();
	void FILL();
	void GET();
	void DEL();
	void AUTOREF();
	void REFRESH();
	void SET_SPRITE();
	void MOVE_SPRITE_TO();
	void MOVE_SPRITE_DIST();
	void SHOW_SPRITE();
	void GET_SPRITE_TILE();
	void GET_SPRITE_X();
	void GET_SPRITE_Y();
	void GET_SPRITE_TILED_X();
	void GET_SPRITE_TILED_Y();
	void ENABLE_SPRITES();
	void RESET_SPRITES();
	void CHECK_SPRITE_COLLISION();
}
