#pragma once
#include "t_string.h"
#include "t_function_ptr.h"

namespace PTML
{
	t_function_ptr get_cmd_pointer(const t_string& cmd);

	void COLOR();
	void COLOR_F();
	void COLOR_B();
	void COLOR_BD();
	void VARS();
	void PRINT();
	void PRINTL();
	void VAR();
	void EXIT();
	void HALT();
	void CLS();
	void PAL();
	void CHR();
	void LOCATE();
	void INC();
	void DEC();
	void ADD();
	void SUB();
	void MUL();
	void DIV();
	void DIVR();
	void POW();
	void SQRT();
	void RND();
	void SWAP();
	void FSCR();
	void CSR_SET();
	void TILE_NEW();
	void TILE_ADD();
	void TILE_LIST();
	void PUT();
	void GET();
	void LIST();
	void RUN();
	void END();
	void NEW();
	void SAVE();
	void LOAD();
	void FILES();
	void GOTO();
	void GOTO_IFE();
	void GOTO_IFNE();
	void GOTO_IFG();
	void GOTO_IFGE();
	void GOTO_IFL();
	void GOTO_IFLE();
	void CALL();
	void CALL_IFE();
	void CALL_IFNE();
	void CALL_IFG();
	void CALL_IFGE();
	void CALL_IFL();
	void CALL_IFLE();
	void RET();
}
