#pragma once

namespace PTML
{
	void COLOR();
	void COLOR_MONO();
	void COLOR_MULTI();
	void COLOR_SETF();
	void COLOR_SETB();
	void COLOR_SETBR();
	void COLOR_GETF();
	void COLOR_GETB();
	void COLOR_GETBR();
	void PRINT();
	void PRINTL();
	void PRINTF();
	void CLS();
	void PAL();
	void CHR();
	void LOCATE();
	void SCR_FULL();
	void CSR_ON();
	void CSR_OFF();
	void TILE_NEW();
	void TILE_ADD();
	void TILE_SETC();
	void TILE_GETC();
	void TILE_SETF();
	void TILE_GETF();
	void TILE_SETB();
	void TILE_GETB();
	void TILE_SETP();
	void TILE_GETP();
	void PUT();
	void RECT();
	void FILL();
	void GET();
	void DEL();
	void SCR_ON();
	void SCR_OFF();
	void REFRESH();
}
