#pragma once

namespace PTML
{
	void COLOR();
	void COLOR_Q();
	void COLOR_MONO();
	void COLOR_MULTI();
	void COLOR_SETF();
	void COLOR_SETB();
	void COLOR_SETBR();
	void COLOR_GETF();
	void COLOR_GETB();
	void COLOR_GETBR();
	void PRINT();
	void PRINTL();
	void PRINTF();
	void CLS();
	void PAL();
	void CHR();
	void PAL_Q();
	void CHR_Q();
	void PAL_RESET();
	void CHR_RESET();
	void PAL_SAVE();
	void PAL_LOAD();
	void CHR_SAVE();
	void CHR_LOAD();
	void LOCATE();
	void SCR_FULL();
	void CSR_ON();
	void CSR_OFF();
	void TILE_NEW();
	void TILE_ADD();
	void TILE_Q();
	void TILE_SETP();
	void TILE_GETP();
	void TILE_SAVE();
	void TILE_LOAD();
	void PUT();
	void RECT();
	void RECT_DEL();
	void LINE_H();
	void LINE_V();
	void FILL();
	void GET();
	void DEL();
	void SCR_ON();
	void SCR_OFF();
	void REFRESH();
}
