#include "PTML_shared_headers.h"
#include "PTML_ALL.h"
#include "PTML_PROGRAM.h"
#include "PTML_VARS.h"
#include "PTML_CTFLOW.h"
#include "PTML_MATH.h"
#include "PTML_GRAPHICS.h"
#include "PTML_FILESYSTEM.h"
#include "PTML_INPUT.h"
#include "PTML_SOUND.h"

t_function_ptr PTML::get_cmd_pointer(const t_string& cmd)
{
	// === PROGRAM MANAGEMENT ===
	CMD("LIST", LIST);
	CMD("NEW", NEW);
	CMD("RENUM", RENUM);
	CMD("SAVE", SAVE);
	CMD("LOAD", LOAD);
	CMD("PROG", PROG);

	// === SYSTEM CONTROL ===
	CMD("RUN", RUN);
	CMD("END", END);
	CMD("HALT", HALT);
	CMD("EXIT", EXIT);
	CMD("RESET", RESET);
	CMD("PAUSE", PAUSE);

	// === MEMORY ===
	CMD("SET", SET);
	CMD("DIM", ARR_DIM);
	CMD("LEN", ARR_LEN);
	CMD("SWAP", SWAP);
	CMD("MEMCLR", MEMCLR);

	// === MATH ===
	CMD("INC", INC);
	CMD("DEC", DEC);
	CMD("ADD", ADD);
	CMD("SUB", SUB);
	CMD("MUL", MUL);
	CMD("DIV", DIV);
	CMD("DIVR", DIVR);
	CMD("POW", POW);
	CMD("SQRT", SQRT);
	CMD("RND", RND);

	// === GOTO ===
	CMD("GOTO", GOTO);
	CMD("GOTO.E", GOTO_IFE);
	CMD("GOTO.NE", GOTO_IFNE);
	CMD("GOTO.GT", GOTO_IFG);
	CMD("GOTO.GTE", GOTO_IFGE);
	CMD("GOTO.LT", GOTO_IFL);
	CMD("GOTO.LTE", GOTO_IFLE);
	CMD("GOTO.K", GOTO_IFKEY);
	CMD("GOTO.NK", GOTO_IFNKEY);

	// === CALL/RET ===
	CMD("CALL", CALL);
	CMD("CALL.E", CALL_IFE);
	CMD("CALL.NE", CALL_IFNE);
	CMD("CALL.GT", CALL_IFG);
	CMD("CALL.GTE", CALL_IFGE);
	CMD("CALL.LT", CALL_IFL);
	CMD("CALL.LTE", CALL_IFLE);
	CMD("CALL.K", CALL_IFKEY);
	CMD("CALL.NK", CALL_IFNKEY);
	CMD("RET", RET);

	// === FILESYSTEM ===
	CMD("FILES", FILES);
	CMD("RENAME", RENAME);
	CMD("KILL", KILL);
	CMD("OPEN", OPEN);
	CMD("CLOSE", CLOSE);
	CMD("WRITE", WRITE);
	CMD("READ", READ);
	CMD("EOF", FEOF);

	// === KEYBOARD INPUT ===
	CMD("INPUT", INPUT);
	CMD("INKEY", INKEY);
	CMD("KFLUSH", KB_FLUSH);

	// === GRAPHICS ===
	CMD("PAL", PAL);
	CMD("CHR", CHR);
	CMD("AUTOREF", AUTOREF);
	CMD("FULLSCR", FULLSCR);
	CMD("REFRESH", REFRESH);
	CMD("CLS", CLS);
	CMD("CURSOR", CURSOR_MODE);
	CMD("LOCATE", LOCATE);
	CMD("PRINT", PRINT);
	CMD("PRINTL", PRINTL);
	CMD("PRINTF", PRINTF);

	// === COLOR REGISTER ===
	CMD("COLOR", COLOR);
	CMD("INK", COLOR_SETF);
	CMD("PAPER", COLOR_SETB);
	CMD("BORDER", COLOR_SETBR);
	CMD("CMODE", COLOR_MODE);
	
	// === TILE REGISTER ===
	CMD("TILE.NEW", TILE_NEW);
	CMD("TILE.ADD", TILE_ADD);
	CMD("TILE.SETC", TILE_SETC);
	CMD("TILE.GETC", TILE_GETC);
	CMD("TILE.SETF", TILE_SETF);
	CMD("TILE.GETF", TILE_GETF);
	CMD("TILE.SETB", TILE_SETB);
	CMD("TILE.GETB", TILE_GETB);
	CMD("TILE.SETP", TILE_SETP);
	CMD("TILE.GETP", TILE_GETP);

	// === TILEBUFFER ===
	CMD("GET", GET);
	CMD("PUT", PUT);
	CMD("DEL", DEL);
	CMD("RECT", RECT);
	CMD("FILL", FILL);

	// === SOUND ===
	CMD("BEEP", BEEP);
	CMD("PLAY", PLAY);
	CMD("LPLAY", LPLAY);

	// === STRING HANDLING ===
	CMD("CONCAT", STR_CONCAT);
	CMD("UPPER", STR_UPPER);
	CMD("LOWER", STR_LOWER);
	CMD("FIND", STR_FIND);
	CMD("SUBSTR", STR_SUBSTR);
	CMD("STRLEN", STR_LEN);
	CMD("ASCII", STR_ASCII);
	CMD("CHAR", STR_CHAR);

	return nullptr;
}
