#pragma once

namespace PTML
{
	void COLOR();
	void COLOR_MONO();
	void COLOR_MULTI();
	void COLOR_SETF();
	void COLOR_SETB();
	void COLOR_SETBR();
	void COLOR_GETF();
	void COLOR_GETB();
	void COLOR_GETBR();
	void PRINT();
	void PRINTC();
	void PRINTL();
	void PRINTF();
	void CLS();
	void PAL();
	void CHR();
	void PAL_OUT();
	void CHR_OUT();
	void PAL_RESET();
	void CHR_RESET();
	void LOCATE();
	void SCR_FULL();
	void CSR_ON();
	void CSR_OFF();
	void TILE_NEW();
	void TILE_ADD();
	void TILE_LIST();
	void TILE_LISTC();
	void PUT();
	void RECT();
	void RECT_DEL();
	void FILL();
	void GET();
	void DEL();
	void SCR_ON();
	void SCR_OFF();
	void REFRESH();
	void SCRL();
	void SCRL_R();
	void SCRL_L();
	void SCRL_U();
	void SCRL_D();
	void BUF_NEW();
	void BUF_PUT();
	void BUF_GET();
}
